name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true

  release:
    runs-on: ubuntu-latest
    needs: ["create-release"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Build
        run: node build.js

      - name: Upload Binary Artifact
        uses: actions/upload-artifact@v3
        with:
          name: StyLua-Plugin
          path: out/StyLua-Plugin.exe

      - name: Upload release assets to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create-release.outputs.upload_url }}
          asset_path: out/StyLua-Plugin.exe
          asset_name: StyLua-Plugin.exe
          asset_content_type: application/octet-stream
